### ISSUE TITLE
Drop utils-space in next version

### ISSUE THREAD

**Issue by necolas** [suitcss/utils#7]
It's not useful or flexible enough.

**Comment by florianbouvot** [comment]
Hi @necolas, I'm curious and I would like to know more about the lack of utility/flexibility of this kind of utilities. Can you explain me or recommend me an article about this? Have you recommendations for managing spaces?

Thank you in advance (*I wonder for a long time*).

**Comment by florianbouvot** [comment]
ping @simonsmith can you give me an opinion ?

**Comment by simonsmith** [comment]
Hey @florianbouvot,

Generally it was found that `utils-space` was too generic to be its own package, as each site/application often has quite different requirements and couldn't be met by something like:

``` css
.u-marginBn { margin-bottom: 0 !important; }
.u-marginBs { margin-bottom: 5px !important; }
.u-marginBm { margin-bottom: 10px !important; }
.u-marginBl { margin-bottom: 20px !important; }
```

On top of that it's generally easier to have a containing component that can look after the spacing of its children, like so:

``` html
<div class="Sidebar">
  <div class="Sidebar-item">
    <!-- component -->
  </div>
  <div class="Sidebar-item">
    <!-- component -->
  </div>
</div>
```

One main benefit of this approach is easily controlling the spacing across breakpoints, which isn't easily done with utility classes. You can read more about that [in this issue](https://github.com/suitcss/suit/issues/70).

That being said, if you need to use spacing classes, then by all means implement them yourself as they can be useful. I wrote [postcss-generate-preset](https://github.com/simonsmith/postcss-generate-preset) to help with mass production of these utils.
