### ISSUE TITLE
Heading utilities

### ISSUE THREAD

**Issue by necolas** [suitcss/utils#8]
I'm planning to add utilities for headings. Something like this:

``` css
.u-headingXXL { color: var(color-headingXXL); font: var(font-headingXXL); }
.u-headingXL { color: var(color-headingXL); font: var(font-headingXL); }
.u-headingL { color: var(color-headingL); font: var(font-headingL); }
.u-headingM { color: var(color-headingM); font: var(font-headingM); }
.u-headingS { color: var(color-headingS); font: var(font-headingS); }
.u-headingXS { color: var(color-headingXS); font: var(font-headingXS); }
.u-headingXXS { color: var(color-headingXXS); font: var(font-headingXXS); }
```

It's easy to extend the scale further at either, end and the naming is clearer than things like `mega`, `giga`, etc. Probably using `!important`.

cc @cameronhunter @philipwalton
